### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by mbrackjr** [nanosonde/sip2rtsp#2]
could it be that the pulsegst images are not public?

echo 'VERSION = "0.0.1-f40365b"' > sip2rtsp/version.py
docker buildx build --build-arg PULSEGST_IMAGE=pulsegst:latest --target=sip2rtsp --tag sip2rtsp:latest .
[+] Building 3.2s (9/9) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                       0.1s
 => => transferring dockerfile: 3.77kB                                                                                                                     0.0s
 => [internal] load .dockerignore                                                                                                                          0.1s
 => => transferring context: 186B                                                                                                                          0.0s
 => resolve image config for docker.io/docker/dockerfile:1.2                                                                                               1.1s
 => CACHED docker-image://docker.io/docker/dockerfile:1.2@sha256:e2a8561e419ab1ba6b2fe6cbdf49fd92b95912df1cf7d313c3e2230a333fdbcc                          0.0s
 => [internal] load build definition from Dockerfile                                                                                                       0.0s
 => [internal] load .dockerignore                                                                                                                          0.0s
 => CANCELED [internal] load metadata for docker.io/library/debian:11                                                                                      1.6s
 => ERROR [internal] load metadata for docker.io/library/pulsegst:latest                                                                                   0.6s
 => CANCELED [internal] load metadata for docker.io/library/debian:11-slim                                                                                 1.5s
------
 > [internal] load metadata for docker.io/library/pulsegst:latest:
------
Dockerfile:1
--------------------
   1 | >>> # syntax=docker/dockerfile:1.2
   2 |
   3 |     # https://askubuntu.com/questions/972516/debian-frontend-environment-variable
--------------------
ERROR: failed to solve: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
make: *** [Makefile:16: local] Error 1

**Comment by nanosonde** [comment]
I have just verified the package settings for nanosonde/pulsegst packages. They are all public now.

Could you please try again?

**Comment by nanosonde** [comment]
But:

why does it try to get the pulsegst image from docker.io?

`ERROR [internal] load metadata for docker.io/library/pulsegst:latest  `

When I run `make local` it uses the image from ghcr.

**Comment by nanosonde** [comment]
no reply. closing.
