### ISSUE TITLE
Error creating devcontainer

### ISSUE THREAD

**Issue by chip131001** [nanosonde/sip2rtsp#7]
I get an error message when starting the container.

How can I solve the problem?
<img width="1818" alt="Bildschirm­foto 2023-03-19 um 09 21 28" src="https://user-images.githubusercontent.com/38818613/226162750-409426a7-7784-462d-bc2f-4f70946d5ac8.png">

**Comment by nanosonde** [comment]
Are you really using the latest commit?

**Comment by nanosonde** [comment]
Oops. Too fast.
Just noticed that you are using the devcontainer. 

I haven‘t fixed that yet. Will do that asap. Stay tuned…

**Comment by nanosonde** [comment]
I also had this for the regular build.

I have fixed this by using the option „--break-system-packages“.

**Comment by nanosonde** [comment]
Add this option here: https://github.com/nanosonde/sip2rtsp/blob/c36cb1e7b5a125fbf3db1ef144f46446abd33a46/Dockerfile#L122

**Comment by chip131001** [comment]
that already exists
<img width="998" alt="Bildschirm­foto 2023-03-19 um 10 59 48" src="https://user-images.githubusercontent.com/38818613/226168032-18607c45-00bb-4b04-b6ab-27e2875d851f.png">

**Comment by nanosonde** [comment]
> that already exists <img alt="Bildschirm­foto 2023-03-19 um 10 59 48" width="998" src="https://user-images.githubusercontent.com/38818613/226168032-18607c45-00bb-4b04-b6ab-27e2875d851f.png">

`pip3 install --break-system-packages -r requirements-dev.txt `

Would be correct. I have just fixed in the main branch.

**Comment by chip131001** [comment]
Ok thanks it works now.
I'm having trouble configuring it.
How can I set up the test source in scrypted?

**Comment by nanosonde** [comment]
Just install the ONVIF plugin and manually add an ONVIF camera.
Use the IP of the docker host and your configured ONVIF port. Default is 10101.
Enter this in scrypted.

**Comment by nanosonde** [comment]
![grafik](https://user-images.githubusercontent.com/2073569/226188354-76833602-5aef-4bd9-ba2f-1d589cf73a52.png)

**Comment by nanosonde** [comment]
I wonder what you currently want to do?

If you are using the devcontainer, then the sip2rtsp python service is not started.
This container is for development purposes for the python code.
Here you would have to manually start the python service with `python3 -m sip2rtsp`.

But you do not need to use that if you do not plan to develop something.

Just checkout the repo and run `make run` or `make run_shell` to run everything.
